version: '3'
services:
  backend:
    container_name: tootroll-be
    build:
      context: backend
    restart: always
    ports:
    - ${HTTP_PORT_BACKEND:-8888}:8888
  frontend:
    container_name: tootroll-fe
    build:
      context: frontend
    restart: always
    volumes:
    - ${PWD:-.}/frontend:/app
    - tmp-node:/app/node_modules
    ports:
    - ${HTTP_PORT_FRONTEND:-8080}:8080
    environment:
    - CHOKIDAR_USEPOLLING=true
    # keep existing node_modules

volumes: 
  tmp-node:
